### ISSUE TITLE
Script error in current version of python and censusgeocode

### ISSUE THREAD

**Issue by jikac** [frankpd/census-batch-geocoder#1]
Hey there,

First off, I want to thank you for all the hard work that you put in developing this program. I have been running into an error that stems from line 126 of your program:
<img width="564" alt="Screen Shot 2021-03-24 at 5 54 36 PM" src="https://user-images.githubusercontent.com/39504924/112398612-3119f800-8cca-11eb-9ae3-0a3fd43c587c.png">
After trying to tinker with your program, it seems to be an issue with problemlist indexing. I have tested my datafile on the most up to date censusgeocode command line tool and it works fine there.

**Comment by JesseKaczmarski** [comment]
Given the length of this issue receiving no interaction, to anyone reading this, I would consider a different approach to geo coding your addresses.

**Comment by jikac** [comment]
Given the length of this issue receiving no interaction, to anyone reading this, I would consider a different approach to geo coding your addresses.
